apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: plexinc/pms-docker
        imagePullPolicy: Always
        ports:
        - containerPort: 32400
          hostPort: 32400
          name: plex
        - containerPort: 32400
          name: plex-udp
          protocol: UDP
        - containerPort: 32469
          name: plex2
        - containerPort: 32469
          name: plex2-udp
          protocol: UDP
        - containerPort: 5353
          name: plex3-udp
          protocol: UDP
        - containerPort: 1900
          name: plex4-udp
          protocol: UDP
        env:
        - name: ADVERTISE_IP
          value: http://192.168.86.202:32400
        - name: HOSTNAME
          value: plex
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: false
        - name: tv
          mountPath: /media/tv
          readOnly: true
        - name: movies
          mountPath: /media/movies
          readOnly: true
        # resources:
          # requests:
            # memory: 128Mi
            # cpu: 250m
          # limits:
            # memory: 1.5Gi
            # cpu: 3.5
      volumes:
      - name: tv
        cephfs:
          monitors:
            - 192.168.86.45:6789
          path: /tv
          user: admin
          secretRef:
            name: ceph-admin-secret
          readOnly: true
      - name: movies
        cephfs:
          monitors:
            - 192.168.86.45:6789
          path: /movies
          user: admin
          secretRef:
            name: ceph-admin-secret
          readOnly: true
      - name: config
        cephfs:
          monitors:
            - 192.168.86.45:6789
          path: /plex/config
          user: admin
          secretRef:
            name: ceph-admin-secret
          readOnly: false
